# Shell variables
# Generated by 'wal'
wallpaper='firewatch_red_blue_green_2560x1440.jpg'

# Special
background='#04142C'
foreground='#d7d2ce'
cursor='#d7d2ce'

# Colors
color0='#04142C'
color1='#ff5260'
color2='#2d998c'
color3='#ebad79'
color4='#2a6f98'
color5='#c16b86'
color6='#7fd1cd'
color7='#d7d2ce'
color8='#969390'
color9='#ff5260'
color10='#2d998c'
color11='#ebad79'
color12='#2a6f98'
color13='#c16b86'
color14='#7fd1cd'
color15='#d7d2ce'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
