# Shell variables
# Generated by 'wal'
wallpaper='new-york-city-3840x2160-neon-nightscape-cgi-4k-12048.jpg'

# Special
background='#14162f'
foreground='#f2f9fd'
cursor='#f2f9fd'

# Colors
color0='#14162f'
color1='#e840af'
color2='#5736eb'
color3='#d39344'
color4='#1077e5'
color5='#ae337f'
color6='#04acd3'
color7='#bddff4'
color8='#232653'
color9='#f372c7'
color10='#836af4'
color11='#e2b073'
color12='#3f96f4'
color13='#cd509e'
color14='#19d1fc'
color15='#f2f9fd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
