#! /bin/sh

bspc monitor -d code-1 code-2 web-1 web-2 music chat-1 chat-2 misc-1 misc-2 misc-3

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bash "$HOME/.config/bspwm/bspwm_colors.sh"

bspc rule -a Emacs state=tiled
bspc rule -a Spotify desktop=music
bspc rule -a Slack desktop=chat-1
bspc rule -a Discord desktop=chat-2
